### ISSUE TITLE
Why square the Z?

### ISSUE THREAD

**Issue by mjack3** [marco-rudolph/cs-flow#17]
Hello @marco-rudolph  I'm following in deep your research (good job btw). 

When the NF model returns the log-likelihood, what is the propose of squaring them? (z variable [here](https://github.com/marco-rudolph/cs-flow/blob/ac78bd192c80866ab8db2b8b483650881e6ea44c/train.py#L68))

Thank you so much. 

PD: Currently I'm working in a [NF implementation](https://arxiv.org/abs/2111.07677) and your answer would help me to understand some key things.

**Comment by marco-rudolph** [comment]
Thank you :)
The NF model does not return the log-likelihood, it is just the output z with same dimension as the input. Since the negative log likelihood of a normal distribution (which is modeled for z) is except to a factor and a constant offset equal to the squared l2-norm of z, it is squared.

Good luck! As far as I know, nobody (including me) was able to reproduce their results yet. And as far as I know, it was not accepted to any conference or journal yet. What you might interpret from this is up to you ;-)

**Comment by mjack3** [comment]
Thanks for your answer.

Yes it's so hard to achieve the results. I'm trying different kind of losses but can't achieve the results.
My best is 98,6 in detection and 97,6 in segmentation, which is far away. I either can match the exact ad params for the flow model :S

In general I get good results in every class except for transistor. For this class my implementation stucks in 96 pixel auroc.

some images are very good "heatmaped"
![image](https://user-images.githubusercontent.com/37028633/162969679-8eb154e3-c611-48f8-964d-380651749286.png)

but in others not

![image](https://user-images.githubusercontent.com/37028633/162969777-ff2d59d0-1835-4a7a-8b9e-5c51972b0a70.png)


Whether you want we could collaborate. I'm in love of the idea this work shows.
