### ISSUE TITLE
different anomaly scores

### ISSUE THREAD

**Issue by ryeowon** [marco-rudolph/cs-flow#21]
Hello.

I'm wondering why anomaly scores in evaluate.py and train.py are different.

https://github.com/marco-rudolph/cs-flow/blob/ea2bb84d06c655da64453d0a71f348ca9678e0ae/evaluate.py#L168

https://github.com/marco-rudolph/cs-flow/blob/ea2bb84d06c655da64453d0a71f348ca9678e0ae/train.py#L68

Thank you.

**Comment by marco-rudolph** [comment]
Hi,
this is just a slip which was not seen as critical since the scaling of the anomaly score does not really matter. For correctness, I fixed the bug with the latest commit.
In terms of the correct negative log likelihood of a normal distribution dividing by 2 is the right choice.

Thank you!
Marco
