### ISSUE TITLE
Without update the weights of EfficientNet during training

### ISSUE THREAD

**Issue by gaowq2017** [marco-rudolph/cs-flow#23]
Hi thanks for sharing the code, i have a question as follow:
    The weights of efficient net haven't update during training. Directly extracting feature using efficient net of pretrained weights is OK? or others? Thank you very much

**Comment by ghost** [comment]
Train the FLOW, not the FE.

**Comment by marco-rudolph** [comment]
We use pretrained weights from ImageNet and do not train them further. These are suitable for detecting anomalies. It does not really make sense to keep training these weights, because in this way features are learned whose density is good to model, but not necessarily helpful for anomaly detection.
